/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.crystals.sco.setrobot.ncr;

import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }

    public void run() {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        junit.run(Sample.class);
    }
}
