/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov.application;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private Logger logger = LoggerFactory.getLogger(App.class);
    private MainFrame mainFrame;

    public static void main(String[] args) {
        App app = new App();
        app.start();
    }

    public void start() {
        logger.info("Start application");
        mainFrame = new MainFrame();
    }
}
